# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customers_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_customers = QtWidgets.QTableWidget(self.centralwidget)
        self.list_customers.setGeometry(QtCore.QRect(0, 20, 701, 471))
        self.list_customers.setObjectName("list_customers")
        self.list_customers.setColumnCount(0)
        self.list_customers.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(700, 20, 96, 134))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_customer_btn = QtWidgets.QPushButton(self.widget)
        self.add_customer_btn.setObjectName("add_customer_btn")
        self.verticalLayout.addWidget(self.add_customer_btn)
        self.edit_customer_btn = QtWidgets.QPushButton(self.widget)
        self.edit_customer_btn.setObjectName("edit_customer_btn")
        self.verticalLayout.addWidget(self.edit_customer_btn)
        self.remove_customer_btn = QtWidgets.QPushButton(self.widget)
        self.remove_customer_btn.setObjectName("remove_customer_btn")
        self.verticalLayout.addWidget(self.remove_customer_btn)
        self.exit_btn = QtWidgets.QPushButton(self.widget)
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout.addWidget(self.exit_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_customer_btn.setText(_translate("MainWindow", "ADD"))
        self.edit_customer_btn.setText(_translate("MainWindow", "EDIT"))
        self.remove_customer_btn.setText(_translate("MainWindow", "REMOVE"))
        self.exit_btn.setText(_translate("MainWindow", "EXIT"))
