# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 921, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.MainContainer = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.MainContainer.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.MainContainer.setContentsMargins(0, 0, 0, 0)
        self.MainContainer.setObjectName("MainContainer")
        self.leftNavigationBar = QtWidgets.QVBoxLayout()
        self.leftNavigationBar.setObjectName("leftNavigationBar")
        self.customerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.customerButton.setObjectName("customerButton")
        self.leftNavigationBar.addWidget(self.customerButton)
        self.reservationButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reservationButton.setObjectName("reservationButton")
        self.leftNavigationBar.addWidget(self.reservationButton)
        self.roomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.roomButton.setObjectName("roomButton")
        self.leftNavigationBar.addWidget(self.roomButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.leftNavigationBar.addItem(spacerItem)
        self.MainContainer.addLayout(self.leftNavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.horizontalLayoutWidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(165, 255, 218);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.customerPage = QtWidgets.QWidget()
        self.customerPage.setObjectName("customerPage")
        self.label = QtWidgets.QLabel(self.customerPage)
        self.label.setGeometry(QtCore.QRect(290, 190, 54, 17))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.customerPage)
        self.reservationPage = QtWidgets.QWidget()
        self.reservationPage.setObjectName("reservationPage")
        self.label_2 = QtWidgets.QLabel(self.reservationPage)
        self.label_2.setGeometry(QtCore.QRect(170, 100, 54, 17))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.reservationPage)
        self.roomPage = QtWidgets.QWidget()
        self.roomPage.setObjectName("roomPage")
        self.pushButton = QtWidgets.QPushButton(self.roomPage)
        self.pushButton.setGeometry(QtCore.QRect(340, 200, 80, 30))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.roomPage)
        self.MainContainer.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.customerButton.setText(_translate("MainWindow", "Customer"))
        self.reservationButton.setText(_translate("MainWindow", "Reservation"))
        self.roomButton.setText(_translate("MainWindow", "Rooms"))
        self.label.setText(_translate("MainWindow", "Reservervation"))
        self.label_2.setText(_translate("MainWindow", "reservation"))
        self.pushButton.setText(_translate("MainWindow", "roombpage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
