# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_customer_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerScene(object):
    def setupUi(self, CustomerScene):
        CustomerScene.setObjectName("CustomerScene")
        CustomerScene.resize(800, 600)
        self.label = QtWidgets.QLabel(CustomerScene)
        self.label.setGeometry(QtCore.QRect(190, 180, 261, 51))
        self.label.setObjectName("label")

        self.retranslateUi(CustomerScene)
        QtCore.QMetaObject.connectSlotsByName(CustomerScene)

    def retranslateUi(self, CustomerScene):
        _translate = QtCore.QCoreApplication.translate
        CustomerScene.setWindowTitle(_translate("CustomerScene", "Hotel"))
        self.label.setText(_translate("CustomerScene", "This is customer scene load from separate file ui"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerScene = QtWidgets.QWidget()
    ui = Ui_CustomerScene()
    ui.setupUi(CustomerScene)
    CustomerScene.show()
    sys.exit(app.exec_())
