# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_customer_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerScene(object):
    def setupUi(self, CustomerScene):
        CustomerScene.setObjectName("CustomerScene")
        CustomerScene.resize(800, 600)
        self.containerQwidget = QtWidgets.QWidget(CustomerScene)
        self.containerQwidget.setGeometry(QtCore.QRect(0, 20, 781, 561))
        self.containerQwidget.setObjectName("containerQwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.containerQwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.containerQwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.containerQwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.containerQwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(CustomerScene)
        QtCore.QMetaObject.connectSlotsByName(CustomerScene)

    def retranslateUi(self, CustomerScene):
        _translate = QtCore.QCoreApplication.translate
        CustomerScene.setWindowTitle(_translate("CustomerScene", "Hotel"))
        self.label.setText(_translate("CustomerScene", "This is customer scene load from separate file ui"))
        self.pushButton_2.setText(_translate("CustomerScene", "PushButton"))
        self.pushButton.setText(_translate("CustomerScene", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerScene = QtWidgets.QWidget()
    ui = Ui_CustomerScene()
    ui.setupUi(CustomerScene)
    CustomerScene.show()
    sys.exit(app.exec_())
