# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_filter_customer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterCustomerDialog(object):
    def setupUi(self, FilterCustomerDialog):
        FilterCustomerDialog.setObjectName("FilterCustomerDialog")
        FilterCustomerDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(FilterCustomerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(FilterCustomerDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.genderLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.genderLabel)
        self.gender = QtWidgets.QComboBox(self.formLayoutWidget)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gender)

        self.retranslateUi(FilterCustomerDialog)
        self.buttonBox.accepted.connect(FilterCustomerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FilterCustomerDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FilterCustomerDialog)

    def retranslateUi(self, FilterCustomerDialog):
        _translate = QtCore.QCoreApplication.translate
        FilterCustomerDialog.setWindowTitle(_translate("FilterCustomerDialog", "Dialog"))
        self.genderLabel.setText(_translate("FilterCustomerDialog", "Gender"))
        self.gender.setItemText(0, _translate("FilterCustomerDialog", "None"))
        self.gender.setItemText(1, _translate("FilterCustomerDialog", "Male"))
        self.gender.setItemText(2, _translate("FilterCustomerDialog", "Female"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FilterCustomerDialog = QtWidgets.QDialog()
    ui = Ui_FilterCustomerDialog()
    ui.setupUi(FilterCustomerDialog)
    FilterCustomerDialog.show()
    sys.exit(app.exec_())
