# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_home_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeScene(object):
    def setupUi(self, HomeScene):
        HomeScene.setObjectName("HomeScene")
        HomeScene.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(HomeScene)
        self.gridLayout.setObjectName("gridLayout")
        self.containerQwidget = QtWidgets.QScrollArea(HomeScene)
        self.containerQwidget.setWidgetResizable(True)
        self.containerQwidget.setObjectName("containerQwidget")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 776, 576))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.summaryContainer = QtWidgets.QVBoxLayout()
        self.summaryContainer.setObjectName("summaryContainer")
        self.subdataContainer = QtWidgets.QGridLayout()
        self.subdataContainer.setObjectName("subdataContainer")
        self.summaryContainer.addLayout(self.subdataContainer)
        self.verticalLayout.addLayout(self.summaryContainer)
        self.chartContainer = QtWidgets.QGridLayout()
        self.chartContainer.setObjectName("chartContainer")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName("pushButton_3")
        self.chartContainer.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.chartContainer)
        self.containerQwidget.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.containerQwidget, 0, 0, 1, 1)

        self.retranslateUi(HomeScene)
        QtCore.QMetaObject.connectSlotsByName(HomeScene)

    def retranslateUi(self, HomeScene):
        _translate = QtCore.QCoreApplication.translate
        HomeScene.setWindowTitle(_translate("HomeScene", "Hotel"))
        self.pushButton_3.setText(_translate("HomeScene", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeScene = QtWidgets.QWidget()
    ui = Ui_HomeScene()
    ui.setupUi(HomeScene)
    HomeScene.show()
    sys.exit(app.exec_())
