# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_home_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeScene(object):
    def setupUi(self, HomeScene):
        HomeScene.setObjectName("HomeScene")
        HomeScene.resize(800, 600)
        self.containerQwidget = QtWidgets.QWidget(HomeScene)
        self.containerQwidget.setGeometry(QtCore.QRect(0, 0, 791, 591))
        self.containerQwidget.setObjectName("containerQwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.containerQwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.grid = QtWidgets.QGridLayout()
        self.grid.setObjectName("grid")
        self.verticalLayout.addLayout(self.grid)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(HomeScene)
        QtCore.QMetaObject.connectSlotsByName(HomeScene)

    def retranslateUi(self, HomeScene):
        _translate = QtCore.QCoreApplication.translate
        HomeScene.setWindowTitle(_translate("HomeScene", "Hotel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeScene = QtWidgets.QWidget()
    ui = Ui_HomeScene()
    ui.setupUi(HomeScene)
    HomeScene.show()
    sys.exit(app.exec_())
