# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qwidgetContainer = QtWidgets.QWidget(self.centralwidget)
        self.qwidgetContainer.setObjectName("qwidgetContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.qwidgetContainer)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container_title = QtWidgets.QWidget(self.qwidgetContainer)
        self.container_title.setStyleSheet("background-color: rgb(248, 250, 252);")
        self.container_title.setObjectName("container_title")
        self.verticalLayout.addWidget(self.container_title)
        self.widget_container = QtWidgets.QWidget(self.qwidgetContainer)
        self.widget_container.setObjectName("widget_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftNavQwidget = QtWidgets.QWidget(self.widget_container)
        self.leftNavQwidget.setEnabled(True)
        self.leftNavQwidget.setStyleSheet("background-color: rgb(248, 250, 252);")
        self.leftNavQwidget.setObjectName("leftNavQwidget")
        self.leftNavigationBar = QtWidgets.QVBoxLayout(self.leftNavQwidget)
        self.leftNavigationBar.setContentsMargins(0, 10, 0, 10)
        self.leftNavigationBar.setSpacing(10)
        self.leftNavigationBar.setObjectName("leftNavigationBar")
        self.customerButton = QtWidgets.QPushButton(self.leftNavQwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customerButton.sizePolicy().hasHeightForWidth())
        self.customerButton.setSizePolicy(sizePolicy)
        self.customerButton.setMinimumSize(QtCore.QSize(150, 40))
        self.customerButton.setFlat(True)
        self.customerButton.setObjectName("customerButton")
        self.leftNavigationBar.addWidget(self.customerButton)
        self.reservationButton = QtWidgets.QPushButton(self.leftNavQwidget)
        self.reservationButton.setMinimumSize(QtCore.QSize(150, 40))
        self.reservationButton.setFlat(True)
        self.reservationButton.setObjectName("reservationButton")
        self.leftNavigationBar.addWidget(self.reservationButton)
        self.roomButton = QtWidgets.QPushButton(self.leftNavQwidget)
        self.roomButton.setMinimumSize(QtCore.QSize(150, 40))
        self.roomButton.setFlat(True)
        self.roomButton.setObjectName("roomButton")
        self.leftNavigationBar.addWidget(self.roomButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.leftNavigationBar.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.leftNavQwidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_container)
        self.stackedWidget.setStyleSheet("background-color: rgb(248, 250, 252);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.widget_container)
        self.horizontalLayout.addWidget(self.qwidgetContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.customerButton.setText(_translate("MainWindow", "Customer"))
        self.reservationButton.setText(_translate("MainWindow", "Reservation"))
        self.roomButton.setText(_translate("MainWindow", "Rooms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
