# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_room_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoomScene(object):
    def setupUi(self, RoomScene):
        RoomScene.setObjectName("RoomScene")
        RoomScene.resize(800, 600)
        self.containerQwidget = QtWidgets.QWidget(RoomScene)
        self.containerQwidget.setGeometry(QtCore.QRect(0, 10, 791, 581))
        self.containerQwidget.setObjectName("containerQwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.containerQwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(self.containerQwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.btnAddRoom = QtWidgets.QPushButton(self.containerQwidget)
        self.btnAddRoom.setStyleSheet("")
        self.btnAddRoom.setFlat(True)
        self.btnAddRoom.setObjectName("btnAddRoom")
        self.headerLayout.addWidget(self.btnAddRoom)
        self.btnEditRoom = QtWidgets.QPushButton(self.containerQwidget)
        self.btnEditRoom.setObjectName("btnEditRoom")
        self.headerLayout.addWidget(self.btnEditRoom)
        self.btnDeleteRoom = QtWidgets.QPushButton(self.containerQwidget)
        self.btnDeleteRoom.setObjectName("btnDeleteRoom")
        self.headerLayout.addWidget(self.btnDeleteRoom)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.cmbLockStatus = QtWidgets.QComboBox(self.containerQwidget)
        self.cmbLockStatus.setObjectName("cmbLockStatus")
        self.headerLayout.addWidget(self.cmbLockStatus)
        self.cmbRoomType = QtWidgets.QComboBox(self.containerQwidget)
        self.cmbRoomType.setObjectName("cmbRoomType")
        self.headerLayout.addWidget(self.cmbRoomType)
        self.cmbFloor = QtWidgets.QComboBox(self.containerQwidget)
        self.cmbFloor.setObjectName("cmbFloor")
        self.headerLayout.addWidget(self.cmbFloor)
        self.verticalLayout.addLayout(self.headerLayout)
        self.tableView = QtWidgets.QTableView(self.containerQwidget)
        self.tableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(RoomScene)
        QtCore.QMetaObject.connectSlotsByName(RoomScene)

    def retranslateUi(self, RoomScene):
        _translate = QtCore.QCoreApplication.translate
        RoomScene.setWindowTitle(_translate("RoomScene", "Hotel"))
        self.label.setText(_translate("RoomScene", "Room"))
        self.btnAddRoom.setText(_translate("RoomScene", "Add Room"))
        self.btnEditRoom.setText(_translate("RoomScene", "Edit Room"))
        self.btnDeleteRoom.setText(_translate("RoomScene", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoomScene = QtWidgets.QWidget()
    ui = Ui_RoomScene()
    ui.setupUi(RoomScene)
    RoomScene.show()
    sys.exit(app.exec_())
