# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_reservation_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReservationScene(object):
    def setupUi(self, ReservationScene):
        ReservationScene.setObjectName("ReservationScene")
        ReservationScene.resize(800, 600)
        self.containerQwidget = QtWidgets.QWidget(ReservationScene)
        self.containerQwidget.setGeometry(QtCore.QRect(0, 10, 791, 581))
        self.containerQwidget.setObjectName("containerQwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.containerQwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.containerQwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(ReservationScene)
        QtCore.QMetaObject.connectSlotsByName(ReservationScene)

    def retranslateUi(self, ReservationScene):
        _translate = QtCore.QCoreApplication.translate
        ReservationScene.setWindowTitle(_translate("ReservationScene", "Hotel"))
        self.label.setText(_translate("ReservationScene", "This is reservation scene load from separate file ui"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReservationScene = QtWidgets.QWidget()
    ui = Ui_ReservationScene()
    ui.setupUi(ReservationScene)
    ReservationScene.show()
    sys.exit(app.exec_())
