# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kai/project/hotel-management/src/ui/ui_room_scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoomScene(object):
    def setupUi(self, RoomScene):
        RoomScene.setObjectName("RoomScene")
        RoomScene.resize(800, 600)
        self.containerQwidget = QtWidgets.QWidget(RoomScene)
        self.containerQwidget.setGeometry(QtCore.QRect(0, 10, 791, 581))
        self.containerQwidget.setObjectName("containerQwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.containerQwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.containerQwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.containerQwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(RoomScene)
        QtCore.QMetaObject.connectSlotsByName(RoomScene)

    def retranslateUi(self, RoomScene):
        _translate = QtCore.QCoreApplication.translate
        RoomScene.setWindowTitle(_translate("RoomScene", "Hotel"))
        self.pushButton.setText(_translate("RoomScene", "PushButton"))
        self.label.setText(_translate("RoomScene", "This is room scene load from separate file ui"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoomScene = QtWidgets.QWidget()
    ui = Ui_RoomScene()
    ui.setupUi(RoomScene)
    RoomScene.show()
    sys.exit(app.exec_())
